# Generated by Django 4.1.3 on 2022-12-04 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_user_is_disiminator_remove_user_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CheckIn',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CheckOut',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
